### PR TITLE
Introduce Go Modules

### PR DESCRIPTION
**Pull request by munisystem**
## WHY

This project uses https://github.com/golang/dep in dependency management. But golang/dep was deprecated and recommends using Go Modules.
cf. https://go.dev/doc/modules/managing-dependencies

## WHAT

I migrate the dependency management tool from golang/dep to Go Modules.

### CODE REVIEW

**Comment by munisystem** [comment]
I checked that I can build a package.

```
~/repos/src/github.com/wantedly/k8nskel munisystem/gomod
$ make deps
go mod download
~/repos/src/github.com/wantedly/k8nskel munisystem/gomod
$ make
CGO_ENABLED=0 go build -tags netgo -installsuffix netgo -ldflags "-w -s -extldflags '-static'" -o bin/k8nskel
~/repos/src/github.com/wantedly/k8nskel munisystem/gomod
$ ./bin/k8nskel
2022/02/15 12:34:41 failed to initialize Kubernetes API client: failed to load in-cluster config: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined

```

**Review by bgpat — APPROVED** [review]
LGTM

**Comment by munisystem** [comment]
I noticed this project uses too old the Go version in Travis CI and this change breaks the CI process.
https://github.com/wantedly/k8nskel/blob/master/.travis.yml#L4

I will create a patch that updates the Go version in CI.

**Comment by munisystem** [comment]
I created PR that bump up Go version to 1.17. https://github.com/wantedly/k8nskel/pull/10

**Pull request merged**
